name: Terraform CI/CD

on: [push]

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out=tf_plan -var 'app_version=${{steps.short-sha.outputs.sha}}'

      - name: Upload plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: ./terraform/tf_plan
          if-no-files-found: error

      - name: Request Approval
        if: success()
        run: |
          echo "Deployment requested for commit $GITHUB_SHA"
          echo "Click here to approve: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: tf-plan

    - name: Terraform Apply
      run: terraform apply -auto-approve ../tf_plan
