name: Terraform CI/CD

on: [push]

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      run: terraform init
    - name: Validate Terraform
      run: terraform validate
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out=tfplan -var 'app_version=${GITHUB_SHA::6}'
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    defaults:
      run:
        working-directory: terraform
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve tfplan
