name: Terraform CI/CD

on: [push]

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      run: terraform init
    - name: Validate Terraform
      run: terraform validate
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out=tfplan -var 'app_version=${{steps.short-sha.outputs.sha}}'
      - name: Upload plan
        uses: actions/upload-artifact@v2
        with:
          name: tf-plan
          path: tf_plan
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    defaults:
      run:
        working-directory: terraform
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      run: terraform init
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: tf_plan
        path: tf_plan
    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve tfplan
