name: Terraform Plan Apply

on:
  push:
    branches:
      - 'master'
    paths:
      - 'terraform/**'
      - 'test-app/**'

# We are passing service account json key secret in GOOGLE_CREDENTIALS
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy:
    name: Terraform Plan Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        id : init
        run: terraform init

      - name: Validate Terraform
        id: validate
        run: terraform validate

        # We use this actions to produce a smaller SHA to use it as container tag.
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

        # We run Terraform apply immediately as this workflow runs on merge. Reviews/Approvals have been already done.
      - name: Terraform Apply
        run: terraform apply -auto-approve -var 'app_version=${{steps.short-sha.outputs.sha}}'
